[build]
  # Build command
  command = "npm run build"
  
  # Output directory
  publish = "dist"
  
  # Node.js version
  environment = { NODE_VERSION = "18" }

[build.environment]
  # Build environment variables (set in Netlify dashboard)
  # VITE_API_URL = "https://your-backend-domain.com"

# SPA redirect rules for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache fonts
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"